### ISSUE TITLE
Protobuf typo

### ISSUE THREAD

**Issue by ianshefferman** [carbonblack/cbapi#10]
I noticed a typo in this enum: https://github.com/carbonblack/cbapi/blob/master/server_apis/proto/sensor_events.proto#L99

I believe it should be `filetypeUniversalBin`, not `filetypeUniverasalBin`.

Is this typo propagated elsewhere at the moment, or is it merely a mistake here? Just want to know if this can/should be fixed or is "a feature" set in stone at this point.

**Comment by scottlundgren** [comment]
@ianshefferman cc @jjguy - one reason that protobufs were chosen for CB application is that they are efficient in terms of bytes-on-wire size.  Part of this efficiency comes - in contrast to JSON and XML - in that the protobuf is not fully self-describing.  So the name of the field can be changed "whenever" so long as the type and relative position stays constant.

So, we can make the change, but there are two caveats:

(1) as @jjguy pointed out, this will require source code changes, including source code changes in both the CB OSX sensor and CB Server.  
(2) this protobuf (in github) is a publicly-facing copy (meaning, the comments have been stripped of profanity) and is therefore not the "master" copy.

As such, I will create an internal ticket to fix this and the fix will eventually bubble out to github.  @ianshefferman - you can feel free to rename yourself in local testing as you see fit.
