### ISSUE TITLE
When listing current sessions for live response the sensor_id was sometimes a unicode string

### ISSUE THREAD

**Issue by askthedragon** [carbonblack/cbapi#73]
```
for session in self.live_response_session_list():
            if session.get('sensor_id') == sensor_id and session.get('status') == "active":
                target_session = session
                break
```
In this code block on 5.1.0 I saw 'sensor_id' == u'9'.  If the sensor_id passed in by the user is an integer the conditional fails.  Continuing on we try to create a new session, but there is already an active one available, so CBER returns a 404.

Proposed fix:
```
for session in self.live_response_session_list():
            if int(session.get('sensor_id')) == sensor_id and session.get('status') == "active":
                target_session = session
                break
```

**Comment by jgarman** [comment]
This looks good. Only issue is that `sensor_id` may not be an integer, but ... if that happens ... I suppose we have bigger problems. I concur with the band-aid
