### ISSUE TITLE
sensor query by hostname should not be case-sensitive

### ISSUE THREAD

**Issue by unixfreak0037** [carbonblack/cbapi#77]
You have this in your documentation, and we've verified this.

> Sensor query strings are case-sensitive substring searches, for both hostname and ip fields. If both hostname and ip fields are specified, only ip is used.

I see no reason for this to be case-sensitive.  Neither DNS nor NetBIOS are case-sensitive, so this just forces us to know what the case sensitivity was when the sensor was added.  Can you change that to be case-insensitive?

**Comment by askthedragon** [comment]
This will have to be put as a feature request for CbER.  I can create this for you.

**Comment by unixfreak0037** [comment]
I would appreciate that.  What is CbER?  Do I have access to that?

On Wed, Apr 20, 2016 at 8:20 AM, Jason McFarland <notifications@github.com>
wrote:

> This will have to be put as a feature request for CbER. I can create this
> for you.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/carbonblack/cbapi/issues/77#issuecomment-212402687>
>



-- 
John W. Davison
unixfreak0037@gmail.com

**Comment by RyPeck** [comment]
@unixfreak0037 you are correct that DNS is case insensitive, but NetBIOS is case sensitive according to Microsoft Docs. I am unsure as to how this plays out in product/on the wire.

> Neither [RFC1001] nor [RFC1002] discusses whether names are case-sensitive. This document clarifies this ambiguity by specifying that because the name space is defined as sixteen 8-bit binary bytes, a comparison MUST be done for equality against the entire 16 bytes. As a result, NetBIOS names are inherently case-sensitive.
> https://msdn.microsoft.com/en-us/library/dd891456.aspx

**Comment by unixfreak0037** [comment]
OK, thanks for clarifying that, I didn't know that.  I'm not sure you'd
ever see that case in a real environment though, but it looks like it's
technically possible.  But I'd rather have the case insensitive matching
then coverage of that edge case.

As a workaround we are just downloading all of the sensors and doing the
match on the client side, but that's a bit inefficient as we have a lot of
endpoints.

On Wed, Apr 20, 2016 at 8:49 AM, Ryan John Peck <notifications@github.com>
wrote:

> @unixfreak0037 <https://github.com/unixfreak0037> you are correct that
> DNS is case insensitive, but NetBIOS is case sensitive according to
> Microsoft Docs. I am unsure as to how this plays out in product/on the wire.
>
> Neither [RFC1001] nor [RFC1002] discusses whether names are
> case-sensitive. This document clarifies this ambiguity by specifying that
> because the name space is defined as sixteen 8-bit binary bytes, a
> comparison MUST be done for equality against the entire 16 bytes. As a
> result, NetBIOS names are inherently case-sensitive.
> https://msdn.microsoft.com/en-us/library/dd891456.aspx
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/carbonblack/cbapi/issues/77#issuecomment-212410587>
>



-- 
John W. Davison
unixfreak0037@gmail.com

**Comment by askthedragon** [comment]
going to close this issue because this doesn't apply to the cbapi codebase, but to the Carbon Black Enterprise Response product itself.  @unixfreak0037  feel free to email us at dev-support@carbonblack.com if you want to continue the discussion.  I'm only curious because I have only seen it all uppercase.
