### ISSUE TITLE
Cb Response API Token Changes after each Web UI login

### ISSUE THREAD

**Issue by slw07g** [carbonblack/cbapi#84]
Not sure if this is a feature or flaw.

**Comment by zacharyestep** [comment]
Hi - This sounds like a CBR support issue more than a problem with this python project if I"m understanding you correctly. Please reach out to our support staff or try community.carbonblack.com. The API key (shown in the webui for CBR) shouldn't change whenever you login.

If you're having problems with the cbapi for python, please update this issue.
